// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlDsIJe80bECBWZQhF9R86ieqqwL-B4-A',
    appId: '1:125781436437:web:61407d820dad933a58061c',
    messagingSenderId: '125781436437',
    projectId: 'alertacanbd',
    authDomain: 'alertacanbd.firebaseapp.com',
    storageBucket: 'alertacanbd.firebasestorage.app',
    measurementId: 'G-2SZGCQXEE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ0WdsoiLD07BHk7k1SkkypJeKyBxzUX8',
    appId: '1:125781436437:android:1838ba949a1814f558061c',
    messagingSenderId: '125781436437',
    projectId: 'alertacanbd',
    storageBucket: 'alertacanbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9KwSy98LRGEEB0pNn-GZ1m4dgjBVnjno',
    appId: '1:125781436437:ios:3e85b8e3b6149f5c58061c',
    messagingSenderId: '125781436437',
    projectId: 'alertacanbd',
    storageBucket: 'alertacanbd.firebasestorage.app',
    iosBundleId: 'com.example.alertacan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9KwSy98LRGEEB0pNn-GZ1m4dgjBVnjno',
    appId: '1:125781436437:ios:3e85b8e3b6149f5c58061c',
    messagingSenderId: '125781436437',
    projectId: 'alertacanbd',
    storageBucket: 'alertacanbd.firebasestorage.app',
    iosBundleId: 'com.example.alertacan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlDsIJe80bECBWZQhF9R86ieqqwL-B4-A',
    appId: '1:125781436437:web:bd0a66702c9af4e758061c',
    messagingSenderId: '125781436437',
    projectId: 'alertacanbd',
    authDomain: 'alertacanbd.firebaseapp.com',
    storageBucket: 'alertacanbd.firebasestorage.app',
    measurementId: 'G-7JX1KH43JG',
  );
}
